### ISSUE TITLE
Yêu cầu - Không kiểm soát chỉnh KQXN khi BN chưa kết thúc điều chỉnh.

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/YeuCau#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `KH Sử dụng API_LIS`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **KH Sử dụng API_LIS**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_huyethoc_cantruthuoctrasai`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại khi kết nối LIS thông qua API thì khi Phòng XN cần thực hiện điều chỉnh lại KQ, hoặc trả KQ thêm đối với XN chưa trả KQ hết của đợt trả KQ trước(bao gồm việc cập nhật lại KQ của những XN đã trả KQ trước đó) thì bị chặn lại, bị báo lỗi là có CLS trước đó đã trả KQ.

Đề nghị bỏ gàng buộc như vậy, khi LIS cập nhật/chỉnh lại KQ thì chỉ kiểm soát các mốc thời gian trả KQ, lấy mẫu, thực hiện y lệnh, vì hiện tại module Labo cũng không bắt đến gàng buộc như vậy, vẫn cho điều chỉnh KQ khi BN chưa xuất viện, và dll cũ cũng không chặn lại như vậy, chặn lại như vậy người dùng phải hủy hết KQ trước đó rồi làm lại từ đầu.
Như hình dưới BN có 3 CLS, cái HH11 đã trả KQ trước đó, giờ trả thêm kết quả cho XN khác, trong dl đầu vào thì vẫn có thông tin kết quả của HH11 trước đó(thông tin không thay đổi), nhưng API chặn lại, nếu xài dll cũ thì được. Lưu ý là BN chưa kết thúc điều trị.
![image](https://github.com/user-attachments/assets/2e755803-8e87-41f1-820c-a20214803d63)

**Comment by nghitamhongngoc** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue 
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**:
- Đồng ý thực hiện yêu cầu.
- 
- P/s: các cập nhật mang tính thay đổi qui trình tổ Lập Trình thì nên thông báo hoặc ghi nhân để HT, TK nắm khi cập nhật đơn vị.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-25_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 
---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-25.
👉 Phương án thực hiện: Rà soát quy trình và thực hiện trả kết quả API-LIS giống với quy trình trả kết quả trên module Laboratory.

**Comment by vinh-dh** [comment]
Cho phép cập nhật lại kết quả theo tham số `thuchiencls_phieu01`: [DH.LIS-23-11-2024.zip](https://github.com/user-attachments/files/17879360/DH.LIS-23-11-2024.zip)

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
CLip test lần 1:

https://github.com/user-attachments/assets/2e15be64-78f3-44e0-b9f0-7fc3b9ce35dd

Hình ảnh trả KQ khi BN đã in phiếu 6556/xuất viện.
![image](https://github.com/user-attachments/assets/909c9160-0427-4b29-af5b-e46835078a44)
![image](https://github.com/user-attachments/assets/942f57bf-880d-414c-a8d3-42dfb8d2d373)
