### ISSUE TITLE
Yêu cầu - Report thêm chức năng quyền xem báo cáo xem 4210

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#16]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **24/11/2-2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclong_hrm789`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5435`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/R6NrgJ6Du)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Do hiện tại chức năng Báo cáo Tổng hợp-> Xuất dữ liệu theo 4210 không còn sử dùng thường xuyên như trước nữa nhưng người dùng có phân quyền thường vào báo cáo này xem làm ảnh hưởng chậm dữ liệu.

Hệ thống-> Phân quyền->09-BC Tổng hợp -> 09BC141, 09BC142, 09BC146, 09BC152 thì khi check phân quyền vào 4 mục này người dùng được xem hết
HÌnh phân quyền trên Report
![image](https://github.com/user-attachments/assets/d804017e-a39d-41c5-a0c2-68bcc0923bd3)

Hình khi xem trên Report
![image](https://github.com/user-attachments/assets/ccaae2dc-c5c6-4602-8682-01b6ce087398)

Yêu cầu Report Thêm phân quyền Xem Xuất dữ liệu 4210 /QĐ-BYT và Xuất dữ liệu 130/QĐ-BYT riêng

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-29_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-29.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Reports.exe v.3.24.1126.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411260-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411260-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411260-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Bổ sung chức năng phân quyền menu `Xuất dữ liệu QĐ 4210/QĐ-BYT` và `Xuất dữ liệu QĐ 130/QĐ-BYT (Cập nhật theo QĐ 4750/QĐ-BYT)`.

![image](https://github.com/user-attachments/assets/ae04ab94-2970-472f-9ed4-b182d54fcca0)

![image](https://github.com/user-attachments/assets/163a3932-1e04-4133-9c39-a98b1fd6533b)

- ☑: https://github.com/dhhiswork/YeuCau/issues/16
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Reports.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
- Report đã bổ sung chức năng phân quyền theo yêu cầu !
![image](https://github.com/user-attachments/assets/930a87b6-a1f2-4333-bc04-4d89706e513b)

![image](https://github.com/user-attachments/assets/5b1f41f4-eb58-40cc-bf09-762aac8bf438)
