### ISSUE TITLE
Yêu cầu - Diagnose hỗ trợ tham số cảnh báo và chặn khi không nhập kết luận của Kho CĐHA và Thăm dò chức năng

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả khách hàng`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthotnot_kios2`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Ukii0h6Cr)

Link yêu cầu cũ đã duyệt [https://github.com/dh-his/Phieu_Yeu_Cau/issues/32](url)

Hiện tại các cận lâm sàng có mã nhóm CV2348 là 2 ( Chẩn đoán hình ảnh) và 3 (Thăm dò chức năng) Cổng giám định BHYT 
bắt buộc phải có kết luận. Yêu cầu Diangnose hỗ trợ tham số cảnh báo và chặn khi không nhập kết luận với những cận lâm sàng có mã nhóm như trên để đơn vị tự quyết định.
Hình yêu cầu tại Admin
![image](https://github.com/user-attachments/assets/f1fa9d4f-fbed-4ecc-9eab-dd83fa0027ac)
Hình báo lỗi từ cổng BHYT
![image](https://github.com/user-attachments/assets/13607fad-b0bc-4253-9858-49f8e4e35f3c)

![image](https://github.com/user-attachments/assets/d143b36b-3408-4bd8-847e-f4bd55fa5392)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-29_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-29.

**Comment by vinh-dh** [comment]
Cập nhật cấu trúc: bổ sung tham số `ha.ketluan`:
```
Nội dung kết luận khi thực hiện Chẩn đoán hình ảnh/Thăm dò chức năng người bệnh BHYT.
Giá trị:
- 0: Cho phép nội dung kết luận rỗng.
- 1: Cảnh báo (cho phép lựa chọn) nội dung kết luận rỗng.
- 2: Không cho phép nội dung kết luận rỗng.
```
![image](https://github.com/user-attachments/assets/9021de30-664c-4562-87fb-b3913dc54297)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Diagnose.exe v.3.24.1128.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32411280-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32411280-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32411280-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Bổ sung chức năng kiểm tra theo tham số `ha.ketluan`: Cảnh báo/Chặn nội dung kết luận rỗng khi thực hiện Chẩn đoán hình ảnh/Thăm dò chức năng.

![image](https://github.com/user-attachments/assets/46005cb5-a344-4fb3-8bde-5a8f2138db7b)

![image](https://github.com/user-attachments/assets/0c38eab7-d5fc-49b2-b173-9181aa65e013)

- ☑: https://github.com/dhhiswork/YeuCau/issues/17
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Diagnose.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Diagnose đã bổ sung theo đúng yêu cầu !
![image](https://github.com/user-attachments/assets/804e9647-10c9-4fff-a226-1e82d4324d03)
