### ISSUE TITLE
Yêu cầu - Register hỗ trợ báo cáo theo nơi công tác

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **27/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_bant_todieutri`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/MBHUs1NXp)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
Do Bệnh viện muốn thống kê số lượt nhân viên của bệnh viện đăng ký khám BHYT trong năm về Sở y tế nên yêu cầu công ty hỗ trợ
cụ thể như sau:
Module Register->Báo cáo thống kê-> Lượt đăng ký ban đầu (như hình dưới) bổ sung thêm cột Nơi công tác để đơn vị thuận tiện trong việc báo cáo sở y tế.
![image](https://github.com/user-attachments/assets/aa574e86-9e5a-479d-baf5-d3d74ddc7740)

Hình tại Form Đăng ký khám chữa bệnh tại module Register có nhập nơi công tác
Module Register-> Đăng ký khám chữa bệnh có nhập Nơi công tác (như hình dưới). 
![image](https://github.com/user-attachments/assets/6ec8dc04-f9a9-4a18-aed1-52cf6cf0891c)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-27_** 

- **🧑‍💻 Thực hiện:** @nqhoa1005 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📆 Thời gian hoàn thành dự kiến : **2024-11-27**

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
---
- ✨: Yêu cầu - Register hỗ trợ báo cáo theo nơi công tác

- ![](https://i.imgur.com/YcHaL0J.png)
- ![](https://i.imgur.com/nlyYUek.png)
---
- ⏯️ Chờ upload bản mới

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1125.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411250-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411250-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411250-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi
Merge pull request #1 from code-dh-hospital-training/main

- ✨: Yêu cầu - Register hỗ trợ báo cáo theo nơi công tác ![](https://i.imgur.com/YcHaL0J.png) ![](https://i.imgur.com/YcHaL0J.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/19
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40web--flow-informational?logo=github)](https://github.com/web-flow) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Rgister đã hỗ trợ theo yêu cầu !
![image](https://github.com/user-attachments/assets/ef6334ee-4078-4873-955b-3765dbd973ba)
