### ISSUE TITLE
Yêu cầu - Thực hiện ký số khi với XML lên cổng (test cổng đào tạo)

### ISSUE THREAD

**Issue by nghivanbi** [dhhiswork/YeuCau#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **30/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Phối hợp kiểm tra thử chữ ký số Softdream
Thông tin hệ thống demo-test: 
+ http://demosign.easyca.vn:8080
+ Tài khoản/Mật khẩu:demo_easysign/demo_easysign
+ Serial CTS/PIN:540110beffa622f3ca84bd2f93f0122c/12345678
[CTS-TEST.zip](https://github.com/user-attachments/files/17898570/CTS-TEST.zip)

Công văn liên quan

[CV 4194.pdf](https://github.com/user-attachments/files/17898248/CV.4194.pdf)
[CV kiểm thử kí số.pdf](https://github.com/user-attachments/files/17898249/CV.ki.m.th.ki.s.pdf)
[Phụ lục kí số.pdf](https://github.com/user-attachments/files/17898251/Ph.l.c.ki.s.pdf)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi @nghitamhongngoc 
- **📘 Nội dung:** Gửi tài liệu theo luồng công việc này, những chữ ký để thử...

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Tìm hiểu tài liệu, tạo Postman để thực hiện kiểm thử việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>❌ Từ chối tiếp nhận<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Lý do:** Không đủ thời gian thực hiện

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Vẫn thực hiện tiếp tục công việc 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nqhoa1005** [comment]
- ✔️ **Tiếp nhận công việc** 
- 📖 Mô tả thực hiện : Tìm hiểu tài liệu, tạo Postman để thực hiện kiểm thử
- 📆 Thời gian hoàn thành dự kiến : **2024-12-02**

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1201.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412010-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412010-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412010-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thực hiện ký số khi với XML lên cổng (test cổng đào tạo)

- ✨: Bổ sung chức năng xuất XML có ký số với đối tác SoftDream ![](https://i.imgur.com/wPeXx1J.png) ![](https://i.imgur.com/Vyt5JOO.png)

- ✨: Bổ sung chức năng Gửi cổng đào tạo có kèm ký số với đối tác SoftDream ![](https://i.imgur.com/grF8hAj.png)

- ✨: Thêm cấu hình thông số kết nối với cổng đào tạo. Khi thực hiện các nghiệp vụ có liên quan tới cổng đào tạo sẽ sử dụng những thông tin này. ![](https://i.imgur.com/yM3IxvG.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**:
- Hỗ trợ hướng dẫn các bước để HT, TK có thể hướng dẫn khách hàng: đăng ký cks trên cổng...

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi @nghitamhongngoc 
- **📘 Nội dung:** Phần này chưa cấu hình chữ ký thật vì đối tác mới chỉ mở demo, nên đang tích họp demo. Phần add chữ ký demo thì có hướng dẫn theo công văn. File .cert cũng có trong phần trên trong tài liệu ở trên.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
### ✅KIỂM TRA SẢN PHẨM✅
---------------------------------------------------------------------
👉 **Phân công kiểm tra**: @le-an-87, @lqbinh1987
⌛ **Hạn hoàn thành mong muốn**: 02/12/2024

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
***
> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: gửi dữ liệu xml ký số demo báo lỗi
![ảnh](https://github.com/user-attachments/assets/75afeaf7-da05-48f8-99a2-ec023b462938)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Có thực hiện đăng ký serial của chữ ký demo lên cổng chưa? Cho xin thông tin dữ liệu để Tổ lập trình kiểm tra lại. ![](https://i.imgur.com/lYAPCwi.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: 
1. Cái này bắt buộc phải đăng ký chữ ký đó hay sao?
2. Có cần kết nối chữ ký số gì nữa không?
3. sử dụng chữ ký số khác được không?

***

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Đúng rồi. Phải đăng ký cái seiral đó lên cổng, thì cổng mới lấy cái đó kiểm tra xem đúng serial đó ký vào dữ liệu xml không. Sau này khi có thay đổi serial thì phải lên đăng ký lại.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: có phải kết nối gì nữa không hay admin tự lấy vậy anh.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 
- **📘 Nội dung:** Hiện tại Admin sẽ tự động lấy các thông tin hết, khi nào đối tác đưa chính thức thì Tổ lập trình sẽ có hướng dẫn cấu hình nhé.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1

> 🟥 Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: đã đăng ký vẫn báo lỗi
![ảnh](https://github.com/user-attachments/assets/6ad41cab-1a57-4907-88f8-47b0b9bec335)
![ảnh](https://github.com/user-attachments/assets/ec3c751a-90e1-4ddc-b4b7-0420d3f4506d)

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
data: an_omon_full_26112024
port: 5432

**Comment by hvtuan1987** [comment]
Em test dữ liệu Quận 12 còn lỗi như dưới:
Thông tin kết nối
Dữ liệu:tuan_dbquan12_kyso
Port: 5432
Pass: 123
ip: 192.168.50.79

Hình cấu hình tại Admin
![image](https://github.com/user-attachments/assets/32f9359c-d38a-4aa6-9ff3-02f437078dcd)
HÌnh thêm chữ ký số trên cổng đào tạo BHXH
![image](https://github.com/user-attachments/assets/a75ef8db-6e0f-464a-9db1-28515054a9b1)
Hình ghi nhật ký lỗi
![image](https://github.com/user-attachments/assets/5fdec3b6-fb42-43db-8691-6a33b01bdf2a)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @le-an-87 @lqbinh1987 
- **📘 Nội dung:** Đối tác ký số đã cập nhật, có thể thử lại bằng Admin. ![](https://i.imgur.com/KMlYBJw.png)


---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1203.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412030-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412030-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412030-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thực hiện ký số khi với XML lên cổng (test cổng đào tạo)

- ✨: Cập nhật code

- ☑: https://github.com/dhhiswork/YeuCau/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1203.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412031-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412031-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412031-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thực hiện ký số khi với XML lên cổng (test cổng đào tạo)

- ✨: Cập nhật code

- ☑: https://github.com/dhhiswork/YeuCau/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1203.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412032-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412032-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32412032-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thực hiện ký số khi với XML lên cổng (test cổng đào tạo)

- ✨: Cập nhật code loại bỏ hết namespace attributes theo Yêu cầu của đối tác Ký số ![](https://i.imgur.com/VS2GqiW.png) ![](https://i.imgur.com/3MoKpkR.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/20
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã thử dữ liệu Quận 12 ký số đã ổn !
![image](https://github.com/user-attachments/assets/b04e10bf-6e9f-414a-bd30-222566778426)

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
## Đã hỗ trợ gửi dữ liệu xml4750 có ký số demo
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![ảnh](https://github.com/user-attachments/assets/19fa7900-f933-47c4-95fa-799c1e0c1b7e)
![ảnh](https://github.com/user-attachments/assets/f65012b0-3e32-4b64-8efe-d94ba19b18e4)
> 📘 Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nqhoa1005 
- **📘 Nội dung:** Thực hiện sao rồi?

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue
⌛ **Hạn hoàn thành mong muốn**: 20/12/2024
📘 **Nội dung**: Tích hợp cks thực của đơn vị. Xong code báo lại sẽ tạo group với đơn vị tích hợp.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi 
- **📘 Nội dung:**
  - Hiện đã thực hiện theo công việc này: [Yêu cầu - Tích hợp ký số XML lên cổng BHXH theo tài liệu mới từ đối tác SoftDream](https://github.com/dhhiswork/To_lap_trinh/issues/13)
  - Còn phải phân tích lại ảnh hưởng các đơn vị, xem có cần cập nhật web services không nên thời gian như vậy là không đủ.
  - Đề nghị thời gian theo luồng công việc mà Tổ lập trình đã phân.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: Đồng ý theo luồng: (https://github.com/dhhiswork/To_lap_trinh/issues/13)
- Thực hiện close issue này vì cks demo đã thực hiện xong.
