### ISSUE TITLE
Yêu cầu - ĐĂNG KÝ KCB TAB CHUYỂN TUYẾN - CHẨN ĐOÁN CHO CHỌN NHIỀU ICD

### ISSUE THREAD

**Issue by minhduc2it** [dhhiswork/YeuCau#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **29/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/LSsPsKCCS

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Module Register, Prescription
Nhập thông tin tab Chuyển chuyến:
- ô Chẩn đoán cho chọn nhiều ICD 
- ô Tên bệnh hiển thị: Tên bệnh chính; tên bệnh phụ 1; tên bệnh phụ 2; ...

Hiện tại ô Chẩn đoán chỉ chọn được ICD chính ra tên bệnh, muốn thêm tên bệnh phụ phải gõ tay thêm
Bổ sung cho chọn nhiều ICD nhằm giảm thời gian khi nhập liệu thông tin chuyển tuyến và chính xác hơn

![image](https://github.com/user-attachments/assets/9566ff60-5336-4f82-a1e5-f33f509027f2)

[Video thao tác nhập chẩn đoán phụ](https://gofile.me/78TQg/vzJiG5F34)

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: @minhduc2it 
Chổ này bổ sung thêm một vài biểu mẫu hiển thị các thông tin nhập vào theo yêu cầu này nhé!

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-10_** 

- **🧑‍💻 Thực hiện:** @lequocthong29 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by minhduc2it** [comment]
➕ **BỔ SUNG THÔNG TIN**  ➕ 
---
Hình ảnh giấy chuyển có Chẩn đoán Chính; Chẩn đoán phụ khi nhập vào tab Chuyển tuyến
![image](https://github.com/user-attachments/assets/ac5c347c-f1a6-4957-b9dc-92d6b691a988)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-12.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1212.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412120-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412120-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412120-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - ĐĂNG KÝ KCB TAB CHUYỂN TUYẾN - CHẨN ĐOÁN CHO CHỌN NHIỀU ICD

![](https://i.imgur.com/Debo9j3.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/21
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
✔️ **ĐÃ TIẾP NHẬN**
⌛ Thời gian dự kiến hoàn thành kiểm tra: 13/12/2024

**Comment by minhduc2it** [comment]
✅**HOÀN THÀNH** ✅
     🆗 Kết quả kiểm tra Register đạt yêu cầu
     👉 Các chức năng khác chưa ghi nhận bất thường
---
Đã kiểm tra đúng yêu cầu
![Image](https://github.com/user-attachments/assets/45ea520d-70dc-4430-b9a5-b7fcf8237c89)
