### ISSUE TITLE
Yêu cầu - Laboratory: BV Ô Môn Thêm mã bệnh nhân vào mẫu Bảng kê xét nghiệm để BV đối chiếu với danh sách chi tiết lượt thực hiện xét nghiệm

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#24]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **3/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK QUẬN Ô MÔN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_mabn_bangkexetnghiem_26112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/XLZ5LQSTZ)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BV Ô Môn yêu cầu thêm mã bệnh nhân vào mẫu in Bảng kê xét nghiệm để nhân viên đối chiếu Bảng kê XN với danh sách bệnh nhân trong chi tiết của báo cáo Lượt xét nghiệm chi tiết. Hiện tại danh sách bệnh nhân trong chi tiết của báo cáo Lượt xét nghiệm chi tiết chỉ có mã bệnh nhân còn Bảng kê xét nghiệm thì chỉ có mã khám bệnh gây khó khăn nhân viên kiểm tra đối chiếu

=> Đề xuất chuyển mẫu Bảng kê xét nghiêm qua mẫu tự thiết kế để BV tự thêm mã bệnh nhân hoặc thêm mã bệnh nhân vào mẫu mặc định hiện tại

![](https://i.imgur.com/cp6Vwx4.png)
![](https://i.imgur.com/SawcVSg.png)
![](https://i.imgur.com/SzbWYhO.png)
![](https://i.imgur.com/7pR5NtP.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-12-02.
👉 Thực hiện: Chuyển `Bảng kê xét nghiệm` sang mẫu tự thiết kế.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.1130.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411300-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411300-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32411300-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Chuyển bảng kê xét nghiệm sang mẫu tự thiết kế. Lưu ý: tài khoản đăng nhập có quyền Admin phân hệ sẽ có thêm chức năng `Thiết kế trang in`.

![image](https://github.com/user-attachments/assets/0e7a0877-b925-49e3-91d9-744983d7ce6b)

![image](https://github.com/user-attachments/assets/9c6e0bb9-246b-42cf-a246-e5ac4475ff55)

- ☑: https://github.com/dhhiswork/YeuCau/issues/24
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Laboratory.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 1**
***
Phần mềm DH.Laboratory.exe v.3.24.1201.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Laboratory mới đã có chức năng tự thiết kế mẫu Bảng kê xét nghiệm

- Hình ảnh: 

![](https://i.imgur.com/A40KGmh.png)
![](https://i.imgur.com/s3LY49G.png)
![](https://i.imgur.com/tGAMPAy.png)
![](https://i.imgur.com/Es7BQ76.png)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Mẫu tự thiết kế mặc định không có nhóm loại CLS, không lấy được tuổi bệnh nhân, footer cuối trang, ngày giờ lấy mẫu đang lấy ngày chỉ định 
  - Đề nghị mẫu tự thiết kế mặc định giống với mẫu mặc định cũ để các đơn vị không có nhu cầu chỉnh sửa mẫu có thể sử dụng được luôn, không làm ảnh hưởng các đơn vị khác, không cần hỗ trợ chỉnh lại mẫu tự thiết kế cho các đơn vị

- Hình ảnh lỗi:
Mẫu cũ
![](https://i.imgur.com/rT7IvH3.png)
Mẫu mới
![](https://i.imgur.com/9OSExXZ.png)
![](https://i.imgur.com/sCeuszI.png)



***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH 1**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by vinh-dh** [comment]
1. Lỗi tuổi = 0 ⬅️ Chờ fix.
2. "Para ngaylaymau đang lấy ngày chỉ định" ?!?!?! ⬅️ Anh chưa hiểu. Đây là dữ liệu thông tin `ngaylaymau`:
![image](https://github.com/user-attachments/assets/865b82a0-48de-4505-949d-7e9507561745)

3. "nhóm loại cls" ⬅️ Chờ bổ sung.
4. "không có Footer cuối mỗi trang". Đây là nguyên nhân:
![image](https://github.com/user-attachments/assets/a9e24d67-ffb9-4faf-9018-49ce7eef0954)

------------------------------------
✔️ Đã tiếp nhận 1 và 3.
⏳ Thời gian hoàn thành dự kiến: 2024-12-04.

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 
2. Ngày lấy mẫu không phải lấy từ chidinhcls.giolaymau mà lấy từ pssttcls.ngaydk  phải không anh? cái này áp dụng cho tất cả đơn vị phải không hay chỉ đơn vị này vậy anh? em thấy nó trùng với giờ chỉ định. Anh cho em hỏi  dữ liệu bảng pssttcls phát sinh khi lấy mẫu hay khi chỉ định CLS , ngaydk lấy ngày KCB hay ngày lấy mẫu vậy anh?

![](https://i.imgur.com/s5YR5ej.png)
![](https://i.imgur.com/wLDE1bO.png)

**Comment by vinh-dh** [comment]
`ngaylaymau` của mẫu này là có trước thời điểm xác định `giờ lấy mẫu` (sau này). Để thống nhất, anh chuyển qua lấy `chidinhcls.giolaymau` luôn.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.1204.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412040-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412040-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412040-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Thiết kế lại `Bảng kê xét nghiệm` giống mẫu cũ. Thay đổi `ngaylaymau` lấy từ `chidinhcls.giolaymau`.

![image](https://github.com/user-attachments/assets/6b4e4d3e-45f5-43b8-bad9-6eafbc53445b)

- ☑: https://github.com/dhhiswork/YeuCau/issues/24
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Laboratory.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 2**
***
Phần mềm DH.Laboratory.exe v.3.24.1204.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Mẫu mặc định bảng kê XN đã fix lỗi không lấy được số tuổi, đã có footer ở cuối trang , giờ lấy mẫu đã lấy từ chidinhcls.giolaymau

- Hình ảnh: 

![](https://i.imgur.com/cdz19pN.png)

***


### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Mẫu mặc định bảng kê XN chưa nhóm được CLS theo loại CLS
- Hình ảnh lỗi:
![](https://i.imgur.com/mc3IUu3.png)
![](https://i.imgur.com/3cPso6V.png)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH 2**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.1204.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412041-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412041-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDHLaboratoryexe%2F32412041-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Sửa lỗi: Mẫu mặc định `Bảng kê xét nghiệm` chưa nhóm được CLS theo loại CLS.

![image](https://github.com/user-attachments/assets/05af59f1-5b29-4c89-b8e3-167ce836dc8b)

- ☑: https://github.com/dhhiswork/YeuCau/issues/24
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Laboratory.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 3**
***
Phần mềm DH.Laboratory.exe v.3.24.1204.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Laboratory đã fix Bảng kê XN không nhóm được cls theo loại cls

- Hình ảnh: 

![](https://i.imgur.com/mc3IUu3.png)
![](https://i.imgur.com/WqWP6do.png)
![](https://i.imgur.com/W69Wkp8.png)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
