### ISSUE TITLE
Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#28]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **6/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_songaydieutri_bangay_27112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/opqb1p9Q5)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Admin, Register, Prescription, Treatment, Printer `

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại phần mềm chưa cho phép nhập mẫu Hộ chiếu 9 ký tự gồm: 1 chữ cái + 8 số
-> Đề nghị thêm cách nhập mẫu hộ chiếu này

![](https://i.imgur.com/73WHWuV.png)
![](https://i.imgur.com/iAZpCar.png)
![](https://i.imgur.com/8o3boga.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-02_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1129.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411290-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411290-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32411290-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Cho phép nhập thêm dạng hộ chiếu 9 ký tự (1 chữ, 8 số) ![](https://i.imgur.com/FIXDzaJ.png) ![](https://i.imgur.com/PsbqqQY.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1129.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411290-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411290-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411290-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Cho phép nhập thêm dạng hộ chiếu 9 ký tự (1 chữ, 8 số) ![](https://i.imgur.com/FIXDzaJ.png) ![](https://i.imgur.com/PsbqqQY.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1129.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411290-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411290-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411290-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Cho phép nhập thêm dạng hộ chiếu 9 ký tự (1 chữ, 8 số) ![](https://i.imgur.com/FIXDzaJ.png) ![](https://i.imgur.com/PsbqqQY.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1129.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411291-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411291-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42411291-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Cho phép nhập thêm dạng hộ chiếu 9 ký tự (1 chữ, 8 số) ![](https://i.imgur.com/FIXDzaJ.png) ![](https://i.imgur.com/PsbqqQY.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1129.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411290-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411290-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411290-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Cho phép nhập thêm dạng hộ chiếu 9 ký tự (1 chữ, 8 số) ![](https://i.imgur.com/FIXDzaJ.png) ![](https://i.imgur.com/PsbqqQY.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '5/12/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalRegister.exe v.3.24.1204.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Register nhận bệnh đã nhập được Hộ chiếu 9 ký tự: 1 chữ + 8 số
  - Hiệu chỉnh thông tin đã nhập được hộ chiếu mới

- Hình ảnh: 

![](https://i.imgur.com/sPDBC4l.png)
![](https://i.imgur.com/YHcv4sC.png)

***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1205.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription nhận bệnh đã nhập được Hộ chiếu 9 ký tự: 1 chữ + 8 số
  - Hiệu chỉnh thông tin đã nhập được Hộ chiếu 9 ký tự: 1 chữ + 8 số
  - Hiệu chỉnh thông tin BANT đã nhập được Hộ chiếu 9 ký tự: 1 chữ + 8 số

- Hình ảnh: 

![](https://i.imgur.com/sCCRQX8.png)
![](https://i.imgur.com/Wg9QnDX.png)
![](https://i.imgur.com/nmZkvBT.png)

***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Form nhập viện báo lỗi CCCD hoặc hộ chiếu không hợp lệ
- Hình ảnh lỗi:
![](https://i.imgur.com/crnvUzT.png)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.1129.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Admin Hiệu chỉnh thông tin bệnh nhân ngoại trú đã nhập được Hộ chiếu 9 ký tự: 1 chữ + 8 số

- Hình ảnh: 

![](https://i.imgur.com/fBbubcr.png)

***

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra 
- **📘 Nội dung:** Nhờ kiểm thử thêm với Treatment. Phần Prescription Tổ lập trình sẽ tiếp tục chỉnh lỗi.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1205.2 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412052-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412052-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412052-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Thêm cách nhập Hộ chiếu mẫu mới gồm 1 chữ cái + 8 số (hiện tại phần mềm chưa cho nhập)

- 🐛: Chỉnh lỗi trên chức năng nhập viện không lưu được. ![](https://i.imgur.com/0gFInYM.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/28
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Treatment.exe v.4.24.1205.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Treatment chỉnh thông tin bệnh nhân đã hỗ trợ nhập Hộ chiếu 9 ký tự: 1 chữ + 8 số cho bệnh nhân và thân nhân

- Hình ảnh: 

![](https://i.imgur.com/GEsDvZ5.png)
![](https://i.imgur.com/32ROgwJ.png)
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalPrinter.exe v.3.24.1205.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Printer Hiệu chỉnh thông tin đã hỗ tợ nhập Hộ chiếu 9 ký tự: 1 chữ + 8 số

- Hình ảnh: 

![](https://i.imgur.com/5OZxuAP.png)

***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 2**
***
Phần mềm Prescription.exe v.3.24.1205.2
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription đã fix lỗi Form nhập viện báo lỗi CCCD hoặc hộ chiếu không hợp lệ

- Hình ảnh: 

![](https://i.imgur.com/7FvnaAR.png)

***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
