### ISSUE TITLE
Yêu cầu - Xử lý gọi hàm in hóa đơn điện tử có dấu tick ký số

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/YeuCau#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **nguoi_ghi_nhan**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `KH sử dụng HDDT VNPT`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **KH sử dụng HDDT VNPT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvclm_trangin_hddt_vnpt`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/TlpIck4J1)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BV yêu cầu khi in trang in hóa đơn, hiện tại mình đang sử dụng hàm này **convertForStoreFkey** để in hóa đơn, trên hóa đơn vừa có thông tin người chuyển đổi, vừa có chữ ký số, nhưng không có dấu tick chổ ký. Theo như @Lộc nói thì phải sử dụng code winform để in đồ họa nền, vì dấu tick nó là dạng hình ảnh:
using (var key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Internet Explorer\PageSetup", true)){key.SetValue("Print_Background", "yes", Microsoft.Win32.RegistryValueKind.String);}
Về kỹ thuật thì cần trao đổi không anh Hậu? nhờ anh trao đổi thêm với Lộc trong group dùm em
![image](https://github.com/user-attachments/assets/d43712f6-7951-4a23-b412-90a22c75a0c2)
.

**Comment by lqbinh1987** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue @nghivanbi 
-  📘 **Nội dung**: Nhờ hỗ trợ.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987 
- **📘 Nội dung:** khi thực hiện in là có lưu về trong thư mục cài đặt, lấy tệp đó in thử xem có bị hông?

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: File html trong thư mục cài đặt thì có dấu tick nhé anh

![image](https://github.com/user-attachments/assets/80f44c29-db38-49e0-84b7-9a5d20ab296a)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Fees.exe v.3.24.1210.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412100-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412100-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FFeesexe%2F32412100-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Xử lý gọi hàm in hóa đơn điện tử có dấu tick ký số ![](https://i.imgur.com/dtwX7Hz.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/3
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Fees.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
Test lần 1
![image](https://github.com/user-attachments/assets/06a3e6b6-b29b-4374-81bc-c1771c4999fd)
