### ISSUE TITLE
Yêu cầu - Cập nhật thời gian SMS hẹn chính xác đến giờ, phút

### ISSUE THREAD

**Issue by nghivanbi** [dhhiswork/YeuCau#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ng**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **30/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN PHỤ SẢN THÀNH PHỐ CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_tk6556_28112024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Thực hiện lấy thời gian hẹn SMS cho HTSS tới giờ phút để thực hiện tạo SMS.

![image](https://github.com/user-attachments/assets/b9d48428-494d-4696-a13e-c9ff49638f02)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi  @nghitamhongngoc 
- **📘 Nội dung:** Mô tả thêm lý do tại sao phải chính xác tới giờ. Vì chức năng gửi tin nhắn hiện tại chỉ lấy danh sách theo ngày để gửi, chưa có chức năng gửi theo giờ. 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: 
- Này là để tạo nội dung hẹn nhé, còn cấu hình thời gian gởi không thay đổi.
- Các dịch vụ chăm sóc của đơn vị cần hẹn bệnh nhận chính xác đế giờ, thêm nữa đây cũng là cải tiến nâng cao chất lượng dịch vụ của bệnh viện. 
- Này là hợp đồng thực hiện theo nhu cầu đơn vị nhé.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi @nghitamhongngoc 
- **📘 Nội dung:** Thực hiện thay đổi ***nội dung gửi tin nhắn*** có thông tin chính xác đến giờ phút giây. Còn việc thực hiện gửi tự động vẫn theo luồng gửi tự động hằng ngày theo nhân viên IT cài đặt tại phía khách hàng. 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Thực hiện thay đổi nội dung gửi tin nhắn có thông tin chính xác đến giờ phút giây. Còn việc thực hiện gửi tự động vẫn theo luồng gửi tự động hằng ngày theo nhân viên IT cài đặt tại phía khách hàng._**

- **⏳ Thời gian hoàn thành:** **_2024-12-05_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: Thực hiện thay đổi nội dung gửi tin nhắn có thông tin chính xác đến giờ phút giây. Còn việc thực hiện gửi tự động vẫn theo luồng gửi tự động hằng ngày theo nhân viên IT cài đặt tại phía khách hàng --> đúng rồi

**Comment by nghivanbi** [comment]
Các loại theo phụ lục này nè:
![image](https://github.com/user-attachments/assets/dc63ae1a-bab3-4647-8a2c-a9717a06f1c8)
![image](https://github.com/user-attachments/assets/886a9feb-1a92-45c0-a8d2-4f77d68a06f8)
![image](https://github.com/user-attachments/assets/348ef7fa-e5a5-448a-96ea-4ce0ae9b62e5)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @
- **📘 Nội dung:** Các loại tin nhắn cho phép thể hiện ngày giờ trên các mẫu tin nhắn sau:
  - Chọc hút noãn
  - Chuyển phôi
  - Tiêm thuốc rụng trứng
  - Bơm tinh trùng vào buồng tử cung

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1130.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411300-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411300-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411300-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Cập nhật thời gian SMS hẹn chính xác đến giờ, phút ![](https://i.imgur.com/Dt2dZwi.png)

- ✨: Bổ sung thêm loại mới Thử thai đối với tin nhắn khoa Hỗ trợ sơ sinh. Bổ sung các para để tạo nội dung tin nhắn: {pGioTaiKham}, {pGioPhutTaiKham}, {pGioPhutGiayTaiKham} lấy theo định dạng giờ 24.

```sql

INSERT INTO current.smsmau

(loaisms,noidung,masms,templatebv,addday1)

VALUES

('Thử thai','BV PHU SAN TPCT kinh moi quy khach {pHoTenKhachHang} den thu thu thai vao ngay {pNgayTaiKham} tai khoa Ho tro sinh san. HOTLINE: 19008665.Tran trong!',

'ivf.thu_thai',

'BV PHU SAN TPCT kinh moi quy khach {pHoTenKhachHang} den thu thu thai vao ngay {pNgayGioTaiKham} tai khoa Ho tro sinh san. HOTLINE: 19008665.Tran trong!',-2)

```

- ✨: Nội dung template có thể chỉnh sửa bằng chương trình quản lý SMS (nếu hông có thể chỉnh noidung, templatebv trong bảng current.smsmau )

- ✨: Các para hỗ trợ: {pHoTenKhachHang} {pTenMuiTiemNgua} {pNamSinh} {pTenKhoaTK} {pGioTaiKham} {pGioPhutTaiKham} {pGioPhutTaiKham} {pGioPhutGiayTaiKham} {pNgayTaiKham}

- ☑: https://github.com/dhhiswork/YeuCau/issues/31
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1130.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411301-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411301-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411301-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Cập nhật thời gian SMS hẹn chính xác đến giờ, phút ![](https://i.imgur.com/Dt2dZwi.png)

- ✨: Bổ sung thêm loại mới Thử thai đối với tin nhắn khoa Hỗ trợ sơ sinh. Bổ sung các para để tạo nội dung tin nhắn: {pGioTaiKham}, {pGioPhutTaiKham}, {pGioPhutGiayTaiKham} lấy theo định dạng giờ 24.

```sql

INSERT INTO current.smsmau

(loaisms,noidung,masms,templatebv,addday1)

VALUES

('Thử thai','BV PHU SAN TPCT kinh moi quy khach {pHoTenKhachHang} den thu thu thai vao ngay {pNgayTaiKham} tai khoa Ho tro sinh san. HOTLINE: 19008665.Tran trong!',

'ivf.thu_thai',

'BV PHU SAN TPCT kinh moi quy khach {pHoTenKhachHang} den thu thu thai vao ngay {pNgayGioTaiKham} tai khoa Ho tro sinh san. HOTLINE: 19008665.Tran trong!',-2)

```

- ✨: Nội dung template có thể chỉnh sửa bằng chương trình quản lý SMS (nếu hông có thể chỉnh noidung, templatebv trong bảng current.smsmau )

- ✨: Các para hỗ trợ: {pHoTenKhachHang} {pTenMuiTiemNgua} {pNamSinh} {pTenKhoaTK} {pGioTaiKham} {pGioPhutTaiKham} {pGioPhutTaiKham} {pGioPhutGiayTaiKham} {pNgayTaiKham}

- ☑: https://github.com/dhhiswork/YeuCau/issues/31
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![image](https://github.com/user-attachments/assets/08aca312-227e-4cbd-ae16-cea6d0bc808b)
