### ISSUE TITLE
Yêu cầu - Treament ghi nhận lại lý do vào viện bệnh nhân trái tuyến nội trú

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbnhidong_sailydovaovien`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh nhân nhập viện vào nội trú không có giấy chuyển tuyến lý do vào viện lúc này Trái tuyến (Hưởng cùng tuyến) đúng.
Nhưng vào Treatment -> Chỉnh đối tượng cập nhật một số thông tin bất kỳ như ngày 5 năm... Lưu lại Treatment ghi nhận cùng tuyến.(Như hình dưới) nên sai
Yêu cầu Treatment khi cập nhật thông tin ghi nhận đúng trạng thái
![image](https://github.com/user-attachments/assets/04abd79b-1a28-4527-a898-0830f545473a)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-06_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
Này là do mô tả mới bị thiếu trường hợp. Vinh coi hỗ  trợ mô tả lại

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận: mô tả bổ sung và fix lỗi
⌛ Thời gian hoàn thành dự kiến: 2024-12-06

**Comment by vinh-dh** [comment]
✔️ Vinh tiếp nhận: mô tả bổ sung tại [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
⌛ Thời gian hoàn thành dự kiến: 2024-12-05.

**Comment by vinh-dh** [comment]
Cập nhật: [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md): Tại Form **Hiệu chỉnh thông tin bệnh nhân nội trú** khi tham số `tuyenbv = 3`
![image](https://github.com/user-attachments/assets/de0f59d3-2425-4515-87d2-e10984b2e2f4)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1205.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412050-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Treament ghi nhận lại lý do vào viện bệnh nhân trái tuyến nội trú

- 🐛: Lỗi - Chỉnh đối tượng bệnh nhân nội trú Treatment (BV Ung Bướu)

- Cập nhật theo mô tả bổ xung:

![image](https://github.com/user-attachments/assets/ceb367e1-1e89-4a9a-9036-5baeeeebf002)

![image](https://github.com/user-attachments/assets/716ea853-a86d-4c4e-ab40-4987f9e9a48c)

![image](https://github.com/user-attachments/assets/fdc4a620-18ec-4e0a-a6a6-456e7eb06354)

- ☑: https://github.com/dhhiswork/Loi/issues/70

- ☑: https://github.com/dhhiswork/YeuCau/issues/35
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác  nhận** 
Treatment đã lấy đúng trạng thái !
![image](https://github.com/user-attachments/assets/11490101-f7dc-4292-ba00-9d997e74b57b)
