### ISSUE TITLE
Yêu cầu - Tính lại số tiền T_BNTT trên 3360

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/YeuCau#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_mong_muon_hoan_thanh](https://img.shields.io/badge/Ngày%20mong%20muốn%20hoàn%20thành-:-blue?style=plastic&logo=github) **23/10/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **to_truong_ghi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvhhtmct_c79`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/RRQvkR9qg)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Report`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại khi BN có sử dụng thuốc thanh toán theo tỷ lệ, ki xuất 3360 cột **t_bntt** trên phần mềm đang tính là **T_BNTT=T_BNTT + T_BNCCT**, xuất 3360 gửi lên cổng thì bị báo lỗi các cột chi tiết cộng lại không bằng với cột T_TONGCHI, nguyên nhân do:
- Cột T_TONGCHI trong 3360 đang là tiền của cột T_TONGCHI_BH của XML, chỉ có chi phí liên quan đến BH, trong khi đó cũng trên mẫu 3360 tại cột T_BNTT đang tính tổng tiền của T_BNTT + T_BNCCT, nên nếu cộng lai 2 cột T_BNTT và T_BHTT nó lệch so với cột T_TONGCHI, lệch đúng số tiền T_BNTT(dư ra phần tiền BN tự trả).
Dưới đây là cổng đối chiếu XML từ phần mềm gửi lên và file 3360 xuất ra từ phần mềm gửi lên cổng.
![image](https://github.com/user-attachments/assets/98aaf6fb-ba9c-4b6c-bd35-e7a0f41d4a26)

![image](https://github.com/user-attachments/assets/7d42cc9b-d47a-49b4-a24d-17594db44003)

- Theo file công thức thì T_BNTT = T_BNCCT.
[Công thức tạm tính 3360 (ngày cập nhật 10-09-2024).xlsx](https://github.com/user-attachments/files/17472164/Cong.th.c.t.m.tinh.3360.ngay.c.p.nh.t.10-09-2024.xlsx)

![image](https://github.com/user-attachments/assets/502ead4f-1429-4993-8d0e-c5cb48861363)

Đề nghị xem xét tính lại chổ T_BNTT trên 3360(2 menu 4750 và 4210) tính lại theo công thức như file, file này các IT có được do trao đổi với nhau, không có nguồn chính thức, nhưng hiện tại cổng cũng đang so sánh và báo lỗi như hình trên, nên BV khong gửi đề nghị thanh toán được. 
###### ![chi_tiet_loi](https://img.shields.io/badge/Thông%20tin%20bệnh%20nhân-:-blue?style=for-the-badge&logo=github)

-  Thông tin BN trong dữ liệu tại Tháng 07/2024, link data và data chỉ có 1 BN đó để dễ kiểm.

**Comment by lqbinh1987** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: Anh @nghitamhongngoc
-  📘 **Nội dung**: Theo như [git cũ](https://github.com/dh-his/Phieu_Yeu_Cau/issues/7) thì đã được duyệt yc, code đã thực hiện cập nhật mô tả, nhưng Tổ code đợi duyệt mô tả? Nhờ anh Bi xem qua, trước đây các mô tả sau khoảng thời gian không ai phản hồi thì code sẽ thực hiện mô tả...

**Comment by nghitamhongngoc** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue 
⌛ **Hạn hoàn thành mong muốn**: 25/11/2024
📘 **Nội dung**:
- Chuyển mô tả qua qua site này.
- Thực hiện mô tả.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-25_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-11-25.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Reports.exe v.3.24.1122.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411220-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411220-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FReportsexe%2F32411220-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Cập nhật chức năng xuất Excel 3360 dữ liệu XML4750, thay đổi cách tính cột: `t_bntt`.

![image](https://github.com/user-attachments/assets/9be8534d-b0a2-431b-a4a9-6fff07c6ea5b)

- ☑: https://github.com/dhhiswork/YeuCau/issues/4
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Reports.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
✅ Test lần 1
![image](https://github.com/user-attachments/assets/d5327273-b4a4-4163-a558-4657e6528d57)
