### ISSUE TITLE
Yêu cầu - Treatment Bổ sung chức năng tạo sẳn liều dùng để chọn lại khi ra toa (BV Tam Nông)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/YeuCau#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_chinhdt_04122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_chinhdt_04122024`](https://gofile.me/78TQg/KjEN6GE0S)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh viện yêu cầu Treatment hỗ trợ chức năng tạo sẳn liều dùng để chọn lại khi ra toa.
```
![ảnh](https://github.com/user-attachments/assets/791650fe-10f5-4c9e-af05-efcf147e39f0)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Hỗ trợ cho phép chọn danh mục theo khoa thực hiện._**

- **⏳ Thời gian hoàn thành:** **_2024-12-14_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
📢 Thảo luận - trao đổi
🧑‍💻 Thảo luận: @le-an-87 
📘 Nội dung: Chưa hình dung được yêu cầu. Đề nghị ghi cụ thể hơn

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @vuongdh 
- **📘 Nội dung:** Tạo danh mục, cho phép chọn, và danh mục này sử dụng theo Khoa thôi, những chức năng hiện tại vẫn giữ nguyên, Hỗ trợ thêm chức năng này.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
✔️ Tiếp nhận và thực hiện công việc
⏳ Thời gian hoàn thành: 2024-12-15

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1216.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412161-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412161-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412161-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Treatment Bổ sung chức năng tạo sẳn liều dùng để chọn lại khi ra toa (BV Tam Nông)

- Cập nhật cấu trúc:

![image](https://github.com/user-attachments/assets/f823f26a-6333-4e7a-a34d-0b5d84479bbb)

```sql

--DO $$

--BEGIN

IF NOT EXISTS (

SELECT 1

FROM information_schema.columns

WHERE table_schema = 'current'

AND table_name = 'dmchidinh'

AND column_name = 'madv'

) THEN

ALTER TABLE current.dmchidinh ADD COLUMN madv VARCHAR(20);

COMMENT ON COLUMN current.dmchidinh.madv IS 'Mã khoa';

END IF;

--lieudung

IF NOT EXISTS (

SELECT 1

FROM information_schema.columns

WHERE table_schema = 'current'

AND table_name = 'dmchidinh'

AND column_name = 'lieudung'

) THEN

ALTER TABLE current.dmchidinh ADD COLUMN lieudung VARCHAR;

COMMENT ON COLUMN current.dmchidinh.lieudung IS 'Liều dùng';

END IF;

--END $$;

```

- Ra toa:

![image](https://github.com/user-attachments/assets/08c5f717-c69c-45a9-861a-f33c78087511)

- Form liều dùng:

- Có thể thêm/sửa/xóa chọn liều dùng

- Lưu: liều dùng được lưu theo khoa cấu hình

![image](https://github.com/user-attachments/assets/a8061f0c-df81-414c-96fd-7a0a356a208c)

- ☑: https://github.com/dhhiswork/YeuCau/issues/40
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
### Đã bổ sung chức năng tạo liều dùng
### 🟥 còn lỗi không xóa được liều dùng
> ✅  Hình ảnh chứng mình cho việc kiểm tra này
![Treatment_xTBz1iykz2](https://github.com/user-attachments/assets/17f40403-ed4e-48fa-ac4d-a410e3f613bb)

**Comment by vuongdh** [comment]
✔️ Tiếp nhận và thực hiện công việc
⏳ Thời gian hoàn thành: 2024-12-21

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1217.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412170-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412170-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412170-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Bổ sung chức năng lấy lại phiếu thủ thuật/ phẫu thuật (BV Nghĩa Hành)

- Cập nhật:

![](https://i.imgur.com/E42r2tW.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/54

- 🐛: Lỗi - Treatment Bổ sung chức năng tạo sẳn liều dùng để chọn lại khi ra toa (BV Tam Nông)

- Cập nhật:

![](https://i.imgur.com/dzuQbqJ.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/40
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Thêm chức năng: Thêm Button để người dùng có thể nhìn vào và thực hiện được thay vì phải nhớ phím tắt `F2`.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-18_** 
  
  - **🧑‍💻 Thực hiện:** @vuongdh 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 2
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
![Treatment_J3apze2ngJ](https://github.com/user-attachments/assets/ae414f65-3a9d-4403-ba3b-dd4e8532532c)

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
