### ISSUE TITLE
Yêu cầu - Register, Prescription hỗ trợ In thông tin kiểm tra thông tuyến

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **14/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN ĐA KHOA TÂM PHÚC   **
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtamphuc_kios`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/V7a11IALR)

Do Bệnh viện cần có thông tin để kiểm tra đối chiếu nhân viên nhập thông tin sai Yêu cầu công ty bổ sung nút IN Tại Form Kiểm tra thông tuyến như hình dưới gồm các thông tin cổng trả về như sau:
(Tốt nhất có thể để cho BV tự thiết kế mẫu in ra).
1. Thông tin kết quả trả về
2. Mã thẻ BHYT
3. Họ tên bệnh nhân
4. Ngày sinh
5. Giới tính
6. Địa chỉ 
7. Hạn thẻ
8. Thời điểm đủ 5 năm liên tục
Thông tin bổ sung thêm như tài khoản và họ tên nhân viên tiếp nhận bệnh, ngày giờ in
Hình thông tin kiểm tra thông tuyến tại Register và Prescription hiện tại
![image](https://github.com/user-attachments/assets/f49e695a-043c-4a76-a808-bd4c3ed1793b)

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**: Bổ sung chức năng in phiếu tại form kiểm tra thông tuyến theo yêu cầu.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-31_** 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1216.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412160-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412160-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412160-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Register, Prescription hỗ trợ In thông tin kiểm tra thông tuyến

- ✨: ***Bổ sung chức năng in thông tin Thông tuyến BHXH*** ![](https://i.imgur.com/DdTOUDF.png) ![](https://i.imgur.com/xH1GXt7.png) ![](https://i.imgur.com/UuEGDdG.png) ![](https://i.imgur.com/vywyZ7E.png)

- ✨: Hỗ trợ các para: `ngaygioin` `DATESYS` `hoten_taikhoanlv` `taikhoanlv`

- ☑: https://github.com/dhhiswork/YeuCau/issues/43
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1216.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412161-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412161-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412161-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Register, Prescription hỗ trợ In thông tin kiểm tra thông tuyến

- ✨: **_Bổ sung chức năng in thông tin Thông tuyến BHXH_** ![](https://i.imgur.com/DdTOUDF.png) ![](https://i.imgur.com/xH1GXt7.png) ![](https://i.imgur.com/UuEGDdG.png) ![](https://i.imgur.com/vywyZ7E.png)

- ✨: Hỗ trợ các para: `ngaygioin` `DATESYS` `hoten_taikhoanlv` `taikhoanlv`

- ☑: https://github.com/dhhiswork/YeuCau/issues/43

- ✨: Bổ sung form tình trạng dinh dưỡng ngoại trú - BV Nhi Đồng

![](https://i.imgur.com/iD41xlx.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/7
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận Register đã hỗ trợ theo yêu cầu, tạm thời BV chưa cần đến Presscription ** 
![image](https://github.com/user-attachments/assets/fabd9647-d733-4f8e-b451-7ac0d68dc9be)
