### ISSUE TITLE
Yêu cầu - Bổ sung tiêu đề mẫu phiếu lãnh thuốc Nghiện Hướng Thần (BV Cù Lao Minh)

### ISSUE THREAD

**Issue by le-an-87** [dhhiswork/YeuCau#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `83600`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cù Lao Minh**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_clm_09_16092024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_clm_09_16092024`](https://gofile.me/78TQg/gnxmn98Pc)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Medicine, Second`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BV Cù Lao Minh đề nghị bổ sung mẫu phiếu lĩnh thuốc Nghiện và mẫu Phiếu lãnh thuốc hướng thần theo mẫu kèm theo.

```
![ảnh](https://github.com/user-attachments/assets/0fdf0eec-f0e8-4e6c-92fe-a96575706c99)
***
Hiện tại phần mềm đã cho thiết kế và đã thiết kế được đa số các chi tiết theo mẫu yêu cầu

- ### [ ]  Chưa thiết kế được tiêu đề: do mẫu Nghiện và hướng thần sử dụng chung mẫu thiết kế nhưng không có para tiêu đề báo cáo nên không tách ra được 2 tiêu đề.
![ảnh](https://github.com/user-attachments/assets/c279ca25-64e6-4e23-979b-e29c740a03d9)

[PHIẾU LĨNH THUỐC TP HƯỚNG TÂM THẦN, THUỐC TP TIỀN CHẤT (1).docx](https://github.com/user-attachments/files/17126443/PHI.U.LINH.THU.C.TP.H.NG.TAM.TH.N.THU.C.TP.TI.N.CH.T.1.docx)
[PHIẾU LĨNH THUỐC TP GÂY NGHIỆN (1).docx](https://github.com/user-attachments/files/17126444/PHI.U.LINH.THU.C.TP.GAY.NGHI.N.1.docx)
***
Chuyển từ issuse https://github.com/dh-hos/Yeu_cau_ho_tro/issues/309

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**:
- Hỗ trợ bổ sung para tiêu đề để hỗ trợ thực hiện yêu cầu.

**Comment by tolaptrinh-issue** [comment]
/


### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:**
  - [ ] Bổ sung tiêu đề mặc định theo yêu cầu
  - [ ] Bổ sung thêm dấu hiệu để phân biệt các loại phiếu này để khi cần Hỗ trợ, triển khai có thể tự thay đổi tiêu đề.

- **⏳ Thời gian hoàn thành:** **_2024-12-17_** 

- **🧑‍💻 Thực hiện:** @vinh-dh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-12-17.

**Comment by vinh-dh** [comment]
![image](https://github.com/user-attachments/assets/a161e6a4-12b2-4c95-af21-c2f307bb2048)

@le-an-87: hiện tại `SecondStore` chưa có mẫu tự thiết kế tại chức năng in phiếu lĩnh. Y/c này của BV là muốn tách mẫu `Lĩnh Nghiện` và mẫu `Lĩnh hướng thần` ra thành mẫu tự thiết kế riêng phải không?

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalSecondStore.exe v.3.24.1215.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalSecondStoreexe%2F32412150-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalSecondStoreexe%2F32412150-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalSecondStoreexe%2F32412150-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Tách mẫu tự thiết kế phiếu lĩnh thuốc `Nghiện` và mẫu phiếu lĩnh thuốc `Hướng thần/Tiền chất` đối với tham số `bcnghienht = 2`. Bổ sung para `tieude` và `tieudephu` cho mỗi phiếu.

![image](https://github.com/user-attachments/assets/b517164a-bf8c-48b1-ade7-ef6e91ed7a1b)

![image](https://github.com/user-attachments/assets/b26fffa2-e0a0-4fda-9556-821b51a20397)

![image](https://github.com/user-attachments/assets/13b7687b-10b5-4feb-b188-a5ee3408a635)

- ☑: https://github.com/dhhiswork/YeuCau/issues/46
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalSecondStore.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalMedicine.exe v.3.24.1215.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalMedicineexe%2F32412150-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalMedicineexe%2F32412150-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalMedicineexe%2F32412150-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Tách mẫu tự thiết kế phiếu lĩnh thuốc `Nghiện` và mẫu phiếu lĩnh thuốc `Hướng thần/Tiền chất` đối với tham số `bcnghienht = 2`. Bổ sung para `tieude` và `tieudephu` cho mỗi phiếu.

![image](https://github.com/user-attachments/assets/b517164a-bf8c-48b1-ade7-ef6e91ed7a1b)

![image](https://github.com/user-attachments/assets/b26fffa2-e0a0-4fda-9556-821b51a20397)

![image](https://github.com/user-attachments/assets/13b7687b-10b5-4feb-b188-a5ee3408a635)

- ☑: https://github.com/dhhiswork/YeuCau/issues/46
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalMedicine.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### ☑️ KẾT QUẢ KIỂM TRA SẢN PHẨM ☑️  
## Lần 1
> ✅  Hình ảnh chứng mình cho việc kiểm tra này:
Second
![HospitalSecondStore_yQUV174qDq](https://github.com/user-attachments/assets/8fbceae1-8bf3-41b8-bafc-f7d25556647b)
Medicine
![HospitalMedicine_HmmhjHlDks](https://github.com/user-attachments/assets/d8611699-1bb3-46ab-a5a6-037ac6798c49)

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
