### ISSUE TITLE
Yêu Cầu - Admin thêm chức năng Xuất file XML Check in không mã hóa

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **20/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthotnot_kios2`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Ukii0h6Cr)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Thỉnh thoảng một số đơn vị khi gởi XML bằng module Admin vừa có check in và có hồ sơ khám chữa bệnh đôi lúc hồ sơ không lên cổng nhưng chưa tìm được nguyên nhân chính xác. Nên phương án 2 là các đơn vị xuất ra file XML và gởi bằng công cụ VAS nhưng VAS thì file check in không mã hóa mới gởi được. Hiện tại thì phần mềm xuất ra file Check in mã hóa. Để hỗ trợ tối đa cho đơn vị nên yêu cầu công ty hỗ trợ như sau:

- Yêu cầu Admin thêm chức năng Xuất file XML Check in và file XML khám chữa bệnh nhưng file Check in KHÔNG MÃ HÓA để khi cần gởi lại check in bằng VAS.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-25_** 

---

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1125.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411250-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411250-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalAdminexe%2F32411250-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu Cầu - Admin thêm chức năng Xuất file XML Check in không mã hóa

- 🐛: Bổ sung chức năng xuất file checkin không mã hóa. Qui trình xuất vẫn bình thường, nhưng sẽ bổ sung thêm 1 tập tin checkin không mã hóa base64, với tên bắt đầu bằng khongmahoabase64 ![](https://i.imgur.com/JMAGjQT.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/5
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalAdmin.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Admin đã hỗ trợ theo yêu cầu !
![image](https://github.com/user-attachments/assets/8d87f1bb-dafa-4f91-bf11-419837c9e848)
