### ISSUE TITLE
Yêu cầu - Hỗ trợ in tem và thông tin tại form tổng hợp dinh dưỡng

### ISSUE THREAD

**Issue by nghivanbi** [dhhiswork/YeuCau#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **16/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
Dữ liệu:
IP: 192.168.50.79; Port: 5434; Data: tuan_dbtpct_bant_todieutri
Chi tiết yều cầu:
- Thực hiện in tem thông tin cho bệnh nhân tại form tổng hợp.
![image](https://github.com/user-attachments/assets/25d76cf1-d2ad-4955-8cc4-01aaac5e5048)
Mẫu tem tự thiết kế với các para tương ứng:
![image](https://github.com/user-attachments/assets/a539ff9f-83d9-423d-8a27-1f384bf99134)
- Lưới tổng hợp thể hiện thêm thông tin buồng bệnh và tên suất ăn
![image](https://github.com/user-attachments/assets/cbb6a1b0-4e96-408d-bbea-e988124ba447)

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue
⌛ **Hạn hoàn thành mong muốn**: 16/12/2024
📘 **Nội dung**: Theo yêu cầu

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-12-16_** 

- **🧑‍💻 Thực hiện:** @vuongdh 

---

<sup>**📢Lưu ý tiếp nhận:**</sup>
<sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
<sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
<sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
<sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vuongdh** [comment]
✔️ Tiếp nhận và Thực hiện công việc
⏳ Thời gian hoàn thành: 2024-12-17

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Nutrition.exe v.4.24.1216.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FNutritionexe%2F42412160-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FNutritionexe%2F42412160-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FNutritionexe%2F42412160-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Hỗ trợ in tem và thông tin tại form tổng hợp dinh dưỡng

- Bổ sung thông tin buồng bệnh, tên suất anh, in tem (tự thiết kế)

![](https://i.imgur.com/iEdBZLQ.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/50
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Nutrition.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue, @vuongdh 
-  📘 **Nội dung**: Hình không thể hiện được nội dung hoàn thành yêu cầu.

**Comment by vuongdh** [comment]
@nghivanbi thấy có nội dung, mà trong git không thấy
![image](https://github.com/user-attachments/assets/a14f5a9b-a75b-4496-be40-59d57240e2b9)
@nghivanbi trong nội dung có ảnh thể hiện

**Comment by nghivanbi** [comment]
Đã hỗ trợ
![image](https://github.com/user-attachments/assets/c3d70dca-c801-4771-9df6-9335c57f6777)
