### ISSUE TITLE
Yêu cầu - Rà soát lại luồng gen QR đối với BIDV

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/YeuCau#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **17/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `
60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tam Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ptamphuc_2211`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

![image](https://github.com/user-attachments/assets/360c6e69-e852-4243-ab7c-bfab7b30fc3f)

Hiện tại khi gen QR thì bên banbk kiểm ra thì báo là sai check sum, phần check sum này hiện tại em không kiểm tra được nhờ code xem lại:
[Dac ta ket noi 2023.zip](https://github.com/user-attachments/files/18144300/Dac.ta.ket.noi.2023.zip)
Cấu hình:
    "Merchant_ID": "12345678",
    "Ten_Merchant": "Test Benh Vien",
    "Terminal_ID": "TAMPHUC",
    "Ten_Terminal": "DA KHOA TAM PHUC",
    "Ma_Quoc_Te": "8062",
    "Ma_Noi_Dia": "1234",
    "So_Tai_Khoan": "108004083034",
    "MasterMerchantCode": "970488"

> _**MaBN**_: `MaBN` - _**MaKB**_: `2411006523` - _**MaBA**_: `MaBA` _**NgayKCB**_: `22/11/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `11` - _**NamKT**_: `2024`

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Rà soát lại qui trình sinh QR, tiếp nhận dữ liệu báo có.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-23_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Đã cập nhật lại theo tài liệu Key tạo md5 là `C03E5654B6656F2FC5F7C5F236CD2DCA`  ![](https://i.imgur.com/xQ1p6z3.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
📢 TRAO ĐỔI📢
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: Cái này cập nhật trên pipelines hay module vậy anh?
![image](https://github.com/user-attachments/assets/205b3688-c290-4208-9a4d-70aaa9bd7ca8)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Nhờ đối tác kiểm tra lại thôi.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @nghivanbi @lqbinh1987 
- **📘 Nội dung:** ***Khi thực hiện triển khai trên môi trường chính thức thì Tổ triển khai cung cấp đầy đủ các thông tin mà đối tác cho Tổ lập trình để thực hiện cấu hình lại môi trường.*** ![](https://i.imgur.com/8zeoTfi.png) ![](https://i.imgur.com/jVgfe0d.png)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
-Test lần: 1
![image](https://github.com/user-attachments/assets/5db1809f-892f-42ac-835b-2963821d26f4)
![image](https://github.com/user-attachments/assets/b937cf01-ec3b-4f18-907a-85b3b618e3dc)
