### ISSUE TITLE
Yêu cầu - Trà Cú: 1. Lập phiếu thủ thuật trên Diagnose, 2. Liên thông dữ liệu Hồ sơ sức khỏe điện tử, 3. Trả kết quả đo loãng xương không cần chọn phim XQ, 4. Thêm mẫu trả kết quả Đo khúc xạ máy

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  Data Đo loãng xương
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_domatdoxuong_12122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/VozQWZAco)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024037125` - _**MaKB**_: `2412000247` - _**MaBA**_: `MaBA` _**NgayKCB**_: `2/12/2024` - _**MaPhong**_: `08` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DO87`
-  Data Đo khúc xạ máy
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_dokhucxamay_12122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6nbNg88DY)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023035529` - _**MaKB**_: `2409004536` - _**MaBA**_: `MaBA` _**NgayKCB**_: `12/9/2024` - _**MaPhong**_: `08` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DO81`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- File yêu cầu: https://gofile.me/78TQg/bP8Zj909T
- Công văn liên thông HSSK: 
  - https://gofile.me/78TQg/3edviQxzh
  - https://gofile.me/78TQg/E5kfNELIJ
- Mẫu trả kết quả Đo khúc xạ máy: https://gofile.me/78TQg/5hNZPnbQv

![](https://i.imgur.com/myKmUQn.png)

1. Thêm chức năng lập phiếu thủ thuật trên phần mềm Diagnose và báo cáo phiếu thủ thuật lên sổ thủ thuật để BV báo cáo, ghi công cho nhân viên (giống như chức năng làm riêng cho BV Tim Mạch CT)
-> BV đang cần gấp chức năng này để báo cáo và tính tiền công cho nhân viên (nếu thực hiện thì làm trước chức năng này hỗ trợ BV)
![](https://i.imgur.com/21x6oMM.png)

2. Liên thông tự động dữ liệu khám chữa bệnh lên hệ thống hồ sơ sức khỏe điện tử (Có công văn và tài liệu kèm theo)

3. Yêu cầu Trả kết quả Chẩn đoán hình ảnh đo loãng xương đang cấu hình kho HA , loại XQKTS để trả kết quả trên phần mềm Diagnose ___không cần chọn loại phim XQ và số lượng phim___, do BV sử dụng kho phim XQ (tham số ha.khophimxq = 1) khi trả kết quả phần mềm bắt chọn loại phim XQ

![](https://i.imgur.com/0Bda5bn.png)
![](https://i.imgur.com/8PnhGPC.png)
![](https://i.imgur.com/aObxdJl.gif)

4. Diagnose Bổ sung mẫu trả kết quả Thăm dò chức năng cho CLS Đo khúc xạ máy (BV đang cấu hình tạm qua loại thủ thuật)
![](https://i.imgur.com/QMg32KV.png)
![](https://i.imgur.com/flxlNIg.png)

**Comment by chauthanhtra** [comment]
### ⁉️ **THẢO LUẬN**
***
Alo anh @nghivanbi 
Có hỗ trợ chức năng nào cho BV không vậy anh? Hay có tính phí gì không? BV hối quá
BV đang cần gấp chức năng nhập phiếu TT/PT trên Diagnose

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**:
- Đồng ý hỗ trợ, ưu tiên mục 2 trước (hiện bv đang làm thủ công xuất XML 4750 gởi) --> gởi thông qua API tài liệu mới cập nhật.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Phân tích yêu cầu để thực hiện.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2025-01-20_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
Chuyển git
