### ISSUE TITLE
Yêu cầu - BV Sa Đéc: Tham số cảnh báo hoặc chặn lưu phiếu TT/PT khi trùng giờ ekip

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN ĐA KHOA SA ĐÉC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_sadec_guixmltudong_16122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/zdpQM1EL4)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BV Sa Đéc yêu cầu thêm tham số cho phép Chọn Chặn không cho lưu hoặc cảnh báo cho phép lưu khi trùng thời gian ekip để người dùng tự quyết định. Hiện tại phần mềm mặc định chặn lưu phiếu TT/PT khi trùng ekip hoặc không chặn mà không có cảnh báo gì hết.
[Theo thông tu số 13/2012/TT-BYT](https://thuvienphapluat.vn/van-ban/The-thao-Y-te/Thong-tu-13-2012-TT-BYT-huong-dan-cong-tac-gay-me-hoi-suc-147690.aspx) Điều 10. 2. m) thì trong 1 số trường hợp 1 nhân viên trong ekip có thể đảm nhiệm 2 TT/PT cùng lúc (ví dụ như bác sĩ gây mê - hồi sức)
![](https://i.imgur.com/cW5j8vT.png)

![](https://i.imgur.com/jLqvxnR.png)
![](https://i.imgur.com/O6NCBnU.png)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Thay đổi mô tả để đáp ứng yêu cầu (🧑‍💻 Thực hiện: @vinh-dh).*** 
    - [ ] ***Cập nhật chức năng theo mô tả  (🧑‍💻 Thực hiện: @vinh-dh, @tolaptrinh-issue ).***
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-19_** 
  
  - **🧑‍💻 Thực hiện:** @vinh-dh 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành mô tả dự kiến: 2024-12-18.

**Comment by vinh-dh** [comment]
✅ HOÀN THÀNH MÔ TẢ ✅
---------------------------------
Cập nhật [Mô tả Kiểm tra thời gian kết quả HA-CN-TT-PT](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Ki%E1%BB%83m%20tra%20th%E1%BB%9Di%20gian%20k%E1%BA%BFt%20qu%E1%BA%A3%20HA-CN-TT-PT.md):
- Bổ sung tham số  `ttpt.canhbaothoigiantrungekip`, kiểm soát thời gian thực hiện TT/PT bị trùng đối với nhân viên trong EkipPT khi lưu phiếu TT/PT.
![image](https://github.com/user-attachments/assets/144166c6-906d-4ca0-9eea-8ec10f613ecb)

- Dựa vào tham số  `ttpt.canhbaothoigiantrungekip`, kiểm soát thời gian thực hiện TT/PT bị trùng đối với nhân viên trong EkipPT khi lưu phiếu TT/PT.
![image](https://github.com/user-attachments/assets/0b7eeafe-5d99-424c-b2d2-755a982f276a)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Góp ý, xác nhận mô tả</sub>

---

- **🧑‍💻 Thảo luận với:** @nghivanbi  @nghitamhongngoc  @le-an-87  @lqbinh1987 
- **📘 Nội dung:** **_Góp ý, xác nhận mô tả công việc_**

---

<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue </sup>

**Comment by tolaptrinh-issue** [comment]
- ***Cập nhật cấu trúc*** ![](https://i.imgur.com/t6ZrN6h.png)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Treatment.exe v.4.24.1218.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412180-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412180-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FTreatmentexe%2F42412180-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - BV Sa Đéc: Tham số cảnh báo hoặc chặn lưu phiếu TT/PT khi trùng giờ ekip

- ✨: Bổ sung chức năng theo tham số `ttpt.canhbaothoigiantrungekip`, thực hiện theo [Mô tả Kiểm tra thời gian kết quả HA-CN-TT-PT](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Ki%E1%BB%83m%20tra%20th%E1%BB%9Di%20gian%20k%E1%BA%BFt%20qu%E1%BA%A3%20HA-CN-TT-PT.md)

- ![](https://i.imgur.com/ueoTt9U.png) ![](https://i.imgur.com/FKxq39J.png) ![](https://i.imgur.com/t6ZrN6h.png) ![](https://i.imgur.com/FkCUyX0.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/55
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Treatment.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1218.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412181-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412181-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412181-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - BV Sa Đéc: Tham số cảnh báo hoặc chặn lưu phiếu TT/PT khi trùng giờ ekip

- ✨: Bổ sung chức năng theo tham số `ttpt.canhbaothoigiantrungekip`, thực hiện theo [Mô tả Kiểm tra thời gian kết quả HA-CN-TT-PT](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Ki%E1%BB%83m%20tra%20th%E1%BB%9Di%20gian%20k%E1%BA%BFt%20qu%E1%BA%A3%20HA-CN-TT-PT.md)

- ![](https://i.imgur.com/ueoTt9U.png) ![](https://i.imgur.com/FKxq39J.png) ![](https://i.imgur.com/t6ZrN6h.png) ![](https://i.imgur.com/FkCUyX0.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/55
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Diagnose.exe v.3.24.1218.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412180-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412180-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FDiagnoseexe%2F32412180-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - BV Sa Đéc: Tham số cảnh báo hoặc chặn lưu phiếu TT/PT khi trùng giờ ekip

- ✨: Bổ sung chức năng theo tham số `ttpt.canhbaothoigiantrungekip`, thực hiện theo [Mô tả Kiểm tra thời gian kết quả HA-CN-TT-PT](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/M%C3%B4%20t%E1%BA%A3%20Ki%E1%BB%83m%20tra%20th%E1%BB%9Di%20gian%20k%E1%BA%BFt%20qu%E1%BA%A3%20HA-CN-TT-PT.md)

![](https://i.imgur.com/ueoTt9U.png)

![](https://i.imgur.com/FKxq39J.png)

![](https://i.imgur.com/t6ZrN6h.png)

![](https://i.imgur.com/FkCUyX0.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/55
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Diagnose.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '21/12/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1220.2
Phần mềm Treatment.exe v.4.24.1219.1
Phần mềm Diagnose.exe v.3.24.1218.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Prescription , Treatment đã hỗ trợ tham số ttpt.canhbaothoigiantrungekip

- Hình ảnh: 
  - Tham số ttpt.canhbaothoigiantrungekip = 1

![firefox_S5WfgMojRq](https://github.com/user-attachments/assets/682688b4-5a6c-46be-85c1-6b7f20d936b5)

  - Tham số ttpt.canhbaothoigiantrungekip = 0

![](https://i.imgur.com/wv1bo5E.gif)


***


### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Phần mềm Diagnose không cảnh báo ekip trùng thời gian TT
- Hình ảnh lỗi:
Data: tra_timmach_ct_stent_6556_amtien_16122024
Port: 5432
![](https://i.imgur.com/zRgQIlU.gif)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại Phần mềm Diagnose chức năng lập phiếu TT/PT.

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⏳ Thời gian hoàn thành dự kiến: 2024-12-24.

**Comment by vinh-dh** [comment]
> ### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**
> 
> - Diễn giải lỗi:
>   - Phần mềm Diagnose không cảnh báo ekip trùng thời gian TT
> - Hình ảnh lỗi:
> Data: tra_timmach_ct_stent_6556_amtien_16122024
> Port: 5432

Đây không phải lỗi nhé @chauthanhtra. trường hợp này BN BHYT nhưng CLS chỉ định lại là BHYT không thanh.
- Chi tiết mô tả:
![image](https://github.com/user-attachments/assets/6615cdc0-1921-4c11-8447-e3167ec484b0)

- Chi tiết trong dữ liệu chỉ định:
![image](https://github.com/user-attachments/assets/8a7b54a0-aab8-42eb-a016-60292e127941)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Diagnose.exe v.3.24.1218.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Diagnose đã hỗ trợ tham số ttpt.canhbaothoigiantrungekip

- Hình ảnh: 

![](https://i.imgur.com/XmL0gp0.gif)

![](https://i.imgur.com/n5zldb4.gif)
***

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
