### ISSUE TITLE
Yêu cầu - PK Đông Tây: Nhận bệnh hiện thông báo bệnh nhân có giấy chuyển tuyến không khi nhận bệnh trái tuyến

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐÔNG TÂY**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_laylaitoa_ngaytaikham_17122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/SMwnfJlaU)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

PK Đông Tây yêu cầu phần mềm Register, Prescription chức năng nhận bệnh mở lại chức năng cảnh báo người dùng "Bệnh nhân trái tuyến có GIẤY CHUYỂN TUYẾN không?"
Hiện tại phần mềm mới không còn hiển thị thông báo này nữa nhân viên phòng khám khi nhận bệnh nhập thiếu thông tin hay nhận bệnh sai, do BH không cho phép phòng khám nhận bệnh trái tuyến, bắt buộc có giấy chuyển tuyến mới được khám. Không cảnh báo nhân viên nhận bệnh nhập sai.
-> Đề xuất có tham số để PK chọn mở cảnh báo hoặc mở lại cho PK Đông Tây

- Phần mềm cũ
![](https://i.imgur.com/zacrma0.gif)

- Phần mềm mới
![](https://i.imgur.com/8u6fFkv.gif)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Kiểm thử và bổ sung theo yêu cầu công việc của luồng này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-23_** 
  
  - **🧑‍💻 Thực hiện:** @lequocthong29 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-23.

**Comment by chauthanhtra** [comment]
PK Medic Miền Đông - 74206 cũng yêu cầu mở lại chức năng này

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lequocthong29
- **📘 Nội dung:** Thêm lại tham số để hỗ trợ chức năng này.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
[Mô tả thêm tham số ](https://github.com/dhhiswork/Mo-ta-he-thong/blob/main/Thong-mo-ta-tham-so-tuy-chon-ap-dung-canh-bao-benh-nhan-trai-tuyen.md)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.1.24.1223.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F12412230-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F12412230-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F12412230-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - PK Đông Tây: Nhận bệnh hiện thông báo bệnh nhân có giấy chuyển tuyến không khi nhận bệnh trái tuyến

- ✨: Bổ sung tham số `nhabbenh.traituyen` hỗ trợ tùy chọn bật `Thông báo bệnh nhân trái tuyến, có giấy chuyển viện không ?`

![](https://i.imgur.com/sr8UvNK.png)

![](https://i.imgur.com/Xocq42y.gif)

- ☑: https://github.com/dhhiswork/YeuCau/issues/61
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalRegister.exe v.1.24.1223.0
***

### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Register có hiện cảnh báo bệnh nhân trái tuyến, có giấy chuyển viện không? nhưng khi chọn không phần mềm vẫn ghi nhận bệnh nhân cùng tuyến, bấm chỉnh chọn có giấy chuyển thì phần mềm chuyển qua trái tuyến
  - Phần mềm ghi nhận sai phiên bản, báo chưa cập nhật phần mềm mới (phần mềm không có trên NAS, tải từ googlestorage
- Hình ảnh lỗi:

![](https://i.imgur.com/Mt6uCcp.gif)

![](https://i.imgur.com/KcNyDUe.png)
![](https://i.imgur.com/U6uGHcf.png)
***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❌ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.1223.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412231-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412231-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalRegisterexe%2F32412231-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - PK Đông Tây: Nhận bệnh hiện thông báo bệnh nhân có giấy chuyển tuyến không khi nhận bệnh trái tuyến

- 🐛: Register có hiện cảnh báo bệnh nhân trái tuyến, có giấy chuyển viện không? nhưng khi chọn không phần mềm vẫn ghi nhận bệnh nhân cùng tuyến, bấm chỉnh chọn có giấy chuyển thì phần mềm chuyển qua trái tuyến

- 🐛: Phần mềm ghi nhận sai phiên bản, báo chưa cập nhật phần mềm mới (phần mềm không có trên NAS, tải từ googlestorage

- ☑: https://github.com/dhhiswork/YeuCau/issues/61
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalRegister.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST 2**
***
Phần mềm HospitalRegister.exe v.3.24.1223.2
Phần mềm Prescription 3.24.1223.7
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm đã fix lỗi ghi nhận sai phiên bản, báo chưa cập nhật phần mềm mới

- Hình ảnh: 
![](https://i.imgur.com/fFqi8V5.png)


***


### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Phần mềm vẫn còn ghi nhận sai trạng thái cùng tuyến, trái tuyến khi chọn
  - Có nhập giấy chuyển tuyến vẫn ghi nhận trái tuyến
  - Prescription nhận bệnh cấp cứu vẫn ghi nhận trái tuyến
- Hình ảnh lỗi:
![](https://i.imgur.com/qUToBLs.gif)
![](https://i.imgur.com/9GraYYj.gif)

***
Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❌ **CHƯA HOÀN THÀNH 2**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by chauthanhtra** [comment]
Chuyển git
