### ISSUE TITLE
Yêu cầu - BV Thới Lai: Kết nối máy xác thực CCCD gắn chip FPT Citizen Identity Card Reader– F.IDR01 vào phần mềm

### ISSUE THREAD

**Issue by chauthanhtra** [dhhiswork/YeuCau#62]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/12/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thới Lai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_thoilai_doc_cccd_fpt_20122024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ToMQWPmvG)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

link file: https://gofile.me/78TQg/VeJ7xbzci
![](https://i.imgur.com/6n7jnhE.png)

BV Thới Lai yêu cầu kết nối máy đọc CCCD gắn chip FPT Citizen Identity Card Reader– F.IDR01 với phần mềm DH
![](https://i.imgur.com/UK1hxdC.png)
Link tài liệu: 
https://gofile.me/78TQg/lSOaAA1q8
https://gofile.me/78TQg/1EyNXsjcA
https://gofile.me/78TQg/ia8tzLTWh

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra @nghivanbi 
- **📘 Nội dung:** Mượn máy để Tổ lập trình tiến hành tích hợp.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by chauthanhtra** [comment]
### ⁉️ **THẢO LUẬN**
***
Anh @nghivanbi, anh có hỗ trợ BV phần này không?
Nếu có hỗ trợ thì anh có thể liên hệ với anh Quang BV Thới Lai mượn máy đọc CCCD hay sao?

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @chauthanhtra 
-  📘 **Nội dung**: Em nhờ đơn vị gởi mình mượn thiết bị nhé.

**Comment by chauthanhtra** [comment]
### ⁉️ **THẢO LUẬN**
***
Bên FPT muốn liên hệ kỹ thuật  để trao đổi qua zalo. Thì liên hệ ai để em thêm vào nhóm. Phần kỹ thuật em không hiểu nên không trao đổi được

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @chauthanhtra
- **📘 Nội dung:** Nhờ add Hậu và Thống vào group giúp.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Trao đổi thông tin trên [group Zalo](https://i.imgur.com/G6QPm5B.png) hỗ trợ kỹ thuật để tìm hiểu cách kết nối.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-24_** 
  
  - **🧑‍💻 Thực hiện:** @lequocthong29 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-24.

**Comment by chauthanhtra** [comment]
chuyển git
