### ISSUE TITLE
Yêu cầu - Tạo repo cho Dashboard BV Phụ Sản

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/YeuCau#63]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">

  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **nguoi_ghi_nhan**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **ngay_hoan_thanh**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `port_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Phần TK đã tạo runner xong cho BV, đề nghị Tổ lập trình tạo code Repo cho BV.
![image](https://github.com/user-attachments/assets/67ac9b86-619c-4732-b655-e82905b04ee1)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Hiện phần này Tổ lập trình vẫn còn trong giai đoạn phát triển sản phẩm. Khi thực hiện xong theo luồng [DUAN - Phân luồng Bệnh Viện Phụ Sản Cần Thơ](https://github.com/dhhiswork/DuAn/issues/7) sẽ thực hiện luôn phần việc luồng này.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Theo luồng công việc này.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-30_** 
  
  - **🧑‍💻 Thực hiện:** @tolaptrinh-issue  
  
  ---
  
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by nghivanbi** [comment]
> ### ✔️ Tiếp nhận và Thực hiện công việc[HD.05]
> * **📘 Mô tả thực hiện:**
>   
>   * [ ]  _**Theo luồng công việc này.**_
> * **⏳ Thời gian hoàn thành:** **_2024-12-30_**
> * **🧑‍💻 Thực hiện:** @tolaptrinh-issue
> 
> 📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue

Hỗ trợ hiển thị như BV Q12 trước cho bệnh viện báo cáo nhé. Các thông số theo mô tả cập nhật theo luồng sau.

**Comment by lqbinh1987** [comment]
> > ### ✔️ Tiếp nhận và Thực hiện công việc[HD.05]
> > 
> > * **📘 Mô tả thực hiện:**
> >   
> >   * [ ]   _**Theo luồng công việc này.**_
> > * **⏳ Thời gian hoàn thành:** **_2024-12-30_**
> > * **🧑‍💻 Thực hiện:** @tolaptrinh-issue
> > 
> > 📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue
> 
> Hỗ trợ hiển thị như BV Q12 trước cho bệnh viện báo cáo nhé. Các thông số theo mô tả cập nhật theo luồng sau.


📢 TRAO ĐỔI📢
---------------------------------------------------------------------
-  👉 **Assign**: @tolaptrinh-issue 
-  📘 **Nội dung**: Hỗ trợ này được không anh? BV cần báo cáo.

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @lqbinh1987
- **📘 Nội dung:** Cụ thể nội dung lại. Nhìn comment không hiểu được.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
- Lấy repo của Q12 cài đặt cho BV Phụ sản, cho hiển thi thông tin như BV Q12
-Test lần: 1
![image](https://github.com/user-attachments/assets/054db9b8-8aea-4574-bfa0-85a2430026ef)
