### ISSUE TITLE
Yêu cầu - Printer In tem xuất bản lẻ và in tem trong phần In phiếu KCB thêm para cột số lượng

### ISSUE THREAD

**Issue by hvtuan1987** [dhhiswork/YeuCau#8]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_mong_muon_hoan_thanh](https://img.shields.io/badge/Ngày%20mong%20muốn%20hoàn%20thành-:-blue?style=plastic&logo=github) **08/11/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **to_truong_ghi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96133`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng khám Đa Khoa Hồng Đức**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_hongduc_dinhmuctonkho`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/hU0LDKKMy)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Printer`

Do trong quá trình triển khai thực tế phát sinh nên Phòng khám yêu cầu hỗ trợ như sau:
1. Printer kho BHYT, kho nhà thuốc: In phiếu KCB: In tem theo các tùy chọn mẫu tự thiết kế bổ sung thêm para Số lượng thuốc, Đơn vị tính
![image](https://github.com/user-attachments/assets/145d32e7-069e-4064-b5bc-af30d309c7c1)
Hình hiện tại khi thiết kế tại tại Form In phiếu KCB
![image](https://github.com/user-attachments/assets/9bb330b8-f370-477a-936c-a3cac3d339c9)

2. Printer nhà thuốc:  Xuất bán lẻ
![image](https://github.com/user-attachments/assets/13d5329b-ca69-42e2-b876-dd58c2c26c6c)
Hình hiện tại khi thiết kế tại tại Form Xuất bán lẻ
![image](https://github.com/user-attachments/assets/96c9acd0-b99d-4077-b8a6-2f25c09a2c57)

Theo luồng của Github này: 
https://github.com/dh-hos/Yeu_cau_ho_tro/issues/369

**Comment by nghitamhongngoc** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @hvtuan1987 
-  📘 **Nội dung**:  không thấy hình, cập nhật hình lại dùm nhé.

**Comment by hvtuan1987** [comment]
@nghitamhongngoc Mẫu tem này á anh !
![image](https://github.com/user-attachments/assets/3619b079-d096-471d-a4e0-46e17745b464)

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @tolaptrinh-issue 
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**:
- Thực hiện hỗ trợ theo yêu cầu: bổ sung para số lượng.

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-25_** 

---

**Comment by hvtuan1987** [comment]
@tolaptrinh-issue Nhờ anh bổ thêm cột para Số lượng và Đơn vị tính luôn á !

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @hvtuan1987 
- **📘 Nội dung:** Nhờ cung cấp thông tin bệnh nhân, kho cụ thể (hoặc nhập giúp Tổ lập trình liên quan tới nghiệp vụ của in tem này)

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by hvtuan1987** [comment]
@tolaptrinh-issue ! Anh vào ngày 6/11/2024 Phần xuất bán lẻ như hình dưới có sẵn thông tin á !
![image](https://github.com/user-attachments/assets/475deb01-6db1-4c2c-8976-6a456fd41ce5)

**Comment by hvtuan1987** [comment]
HÌnh này tại kho lẻ 01 BHYT ngày hôm nay luôn hén anh @tolaptrinh-issue 
![image](https://github.com/user-attachments/assets/41b2bfee-4419-4ebc-8663-23770f16d622)

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1125.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411250-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411250-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411250-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Printer In tem xuất bản lẻ và in tem trong phần In phiếu KCB thêm para cột số lượng

- 🐛: Bổ sung các para vào tem toa thuốc (soluong, soluongstr,dvt) ![](https://i.imgur.com/49MB8GW.png) ![](https://i.imgur.com/Lke5Q08.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/8
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @hvtuan1987 
- **📘 Nội dung:** Kiểm thử lại hết các chức năng giúp Tổ lập trình, mới chỉ kiểm thử ở chỗ bán lẻ, nhưng vì đây là code chung, nên các chức năng còn lại cũng vậy. 

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by hvtuan1987** [comment]
@tolaptrinh-issue 
Hiện tại chổ in tem Số lượng đã ổn nhưng chổ para TENHH không hiển thị được tên thuốc như hình dưới
Sẵn theo luồng này em báo lỗi khi in phiếu 01KCB tại Printer trên bệnh nhân này luôn á
![image](https://github.com/user-attachments/assets/0b45dbcd-b88b-445c-a281-95f705606926)
![image](https://github.com/user-attachments/assets/77414972-3e72-46a8-81fd-0b27e76a4f46)

**Comment by tolaptrinh-issue** [comment]
### <sub>📢 Thảo luận - trao đổi</sub>

---

- **🧑‍💻 Thảo luận:** @hvtuan1987 
- **📘 Nội dung:** Dữ liệu bị lỗi oid nữa rồi. Thử trên dữ liệu khác nhé.

---
<sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1125.1 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411251-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411251-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FHospitalPrinterexe%2F32411251-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- ✨: Yêu cầu - Printer In tem xuất bản lẻ và in tem trong phần In phiếu KCB thêm para cột số lượng

- 🐛: Chỉnh lỗi mất tên hàng hóa khi in tem ![](https://i.imgur.com/aRol7XC.png)

- ☑: https://github.com/dhhiswork/YeuCau/issues/8
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/HospitalPrinter.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Đã tiếp nhận** 
Xác nhận Printer đã hỗ trợ in tem thêm số lượng và đơn vị tính theo yêu cầu !
![image](https://github.com/user-attachments/assets/b910663d-2c3f-4375-9819-14fa3e4e957d)
